name: ci

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        optimize-level: [0, 1, 2]
        target:
          - os: ubuntu-latest
            compiler: gcc
          - os: ubuntu-latest
            compiler: clang
          - os: windows-latest
            compiler: msvc
          - os: windows-latest
            compiler: clang
          - os: windows-latest
            compiler: gcc
          - os: windows-latest
            compiler: clang-cl
    runs-on: ${{ matrix.target.os }}
    steps:
      - uses: actions/checkout@v5
      - name: CI with expand
        shell: pwsh
        run: ./pwsh/ci.ps1 -Compiler '${{ matrix.target.compiler }}' -OptimizeLevel ${{ matrix.optimize-level }} -TestWithExpand
      - name: CI without expand
        shell: pwsh
        run: ./pwsh/ci.ps1 -Compiler '${{ matrix.target.compiler }}' -OptimizeLevel ${{ matrix.optimize-level }} -TestWithoutExpand
