name: ci

on:
  push:
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            kind: gcc
          - os: ubuntu-latest
            kind: clang
          - os: windows-latest
            kind: msvc
          - os: windows-latest
            kind: clang
          - os: windows-latest
            kind: gcc
          - os: windows-latest
            kind: clang-cl
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v5
      - name: CI with expand
        shell: pwsh
        run: ./pwsh/ci.ps1 -Compiler '${{ matrix.kind }}' -TestWithExpand
      - name: CI without expand
        shell: pwsh
        run: ./pwsh/ci.ps1 -Compiler '${{ matrix.kind }}' -TestWithoutExpand